#! /bin/sh -e
# /usr/lib/emacsen-common/packages/install/haskell-mode

# Written by Jim Van Zandt <jrv@vanzandt.mv.com>, borrowing heavily
# from the install scripts for gettext by Santiago Vila
# <sanvila@ctv.es> and octave by Dirk Eddelbuettel <edd@debian.org>.

FLAVOR=$1
PACKAGE=haskell-mode

case ${FLAVOR} in
    emacs|emacs21|xemacs21)
	# emacs21 needs the "syntax" package, see README.md
	# xemacs21 is documented to be unsupported.
	# emacs is part of the debian infrastructure and not a target emacs.
	echo install/${PACKAGE}: Ignoring emacsen flavor ${FLAVOR}
	exit 0
	;;
    *)
	echo install/${PACKAGE}: Handling install for emacsen flavor ${FLAVOR}
	;;
esac

#FLAVORTEST=`echo $FLAVOR | cut -c-6`
#if [ ${FLAVORTEST} = xemacs ] ; then
#    SITEFLAG="-no-site-file"
#else
#    SITEFLAG="--no-site-file"
#fi
FLAGS="${SITEFLAG} -q -batch -l path.el -f batch-byte-compile"

ELDIR=/usr/share/emacs/site-lisp/${PACKAGE}
ELCDIR=/usr/share/${FLAVOR}/site-lisp/${PACKAGE}

# Install-info-altdir does not actually exist. 
# Maybe somebody will write it.
if test -x /usr/sbin/install-info-altdir; then
    echo install/${PACKAGE}: install Info links for ${FLAVOR}
    install-info-altdir --quiet --section "" "" --dirname=${FLAVOR} /usr/info/${PACKAGE}.info.gz
fi

install -m 755 -d ${ELCDIR}
cd ${ELDIR}
FILES=`echo *.el`
cp ${FILES} ${ELCDIR}
cd ${ELCDIR}

cat << EOF > path.el
(setq load-path (cons "." load-path) byte-compile-warnings nil)
EOF
${FLAVOR} ${FLAGS} ${FILES}
# preserve haskell-mode-autoloads.el because it is not byte compiled
rm -f $(echo *.el | grep -v haskell-mode-autoloads.el) path.el

exit 0
